@endpoint = https://67183kcdkf.execute-api.eu-central-1.amazonaws.com/prod

GET {{endpoint}}/hello
###

POST {{endpoint}}/spaces/
Content-Type: application/json

{
    "location": "Valencia",
    "name": "Best Oranges"
}